import type { Metadata } from "next";

import { inter, poppins } from "@/components/fonts/fonts";
import "./globals.css";
import Nav from "@/components/nav/nav";
import ThemeProvider from "@/store/useThemeStore";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.variable} antialiased`}>
        <main>
          <ThemeProvider>
            <Nav />
          </ThemeProvider>
          {children}
        </main>
      </body>
    </html>
  );
}
